#default 공통사항
spring:
  jpa:
    properties:
      hibernate:
        #        show_sql: true 시스템아웃을 통해 찍음
        format_sql: true
        jdbc:
          batch_size: 200
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
## 순환 참조 에러 제거
  main:
    allow-circular-references: true
## Mysql 상세 지정
    database: mysql
## Mysql 기본 설정
  datasource:
    url: ENC(RIpV0YFORoSuop3LAHk9XHU30RDsQ9lNyazeZ7A/Zmyqz69EEf3nsTsD3HiGZrhyUH1u775eCdmwQlSTbM31ulDiVl29DbaKW/7LFg28G43nHP8ODQijSdp4WynYq0Cr)
    username: ENC(JHya4zdkPrjKceTY2xkHYw==)
    password: ENC(EgXQEVAqfj6qieIHR8xelfP2mHdacrh4)
    driver-class-name: com.mysql.cj.jdbc.Driver

## 파일 크기 지정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

## redis 설정
  data:
    redis:
      host: localhost
      port: 6379
      password: ENC(q+nnyCBjvD/icOFPcpH/89PL6imKAqOO)

## AWS 설정
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: evertrip-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
## 대칭키 암호화 설정(개인정보 암호화 시 사용)
symmetricCrypto:
  secret: ENC(kyj221KeDRO2F0MOiV3FJfgRzctOgpptDy+ZtuqI5iXk6+k0p08dfHHu8kjSwJ6jmF49MNR23EA=)
--- # local 환경
spring:
  config:
    activate:
      on-profile: local

# Oauth 설정
  security:
    oauth2:
      naver:
        client-id: ENC(68K3htZeJ3YepfQoQ9q8Be392V96gJtufq2Qju3lSt0=)
        client-secret: ENC(jOshFL4Sjf0urvS5ZFhR/jrvSMG9Dxdw)
        scope: name,email,age,gender,birthday,birthyear,mobile
        client-name: Naver
        authorization-grant-type: authorization_code
        redirect-url: http://localhost:8080/auth/naver/callback
        authorization: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        user-name-attribute: response


jwt:
  secret: ENC(NMYQFZTvflq8xLXcPokP9JbX2L/7XjXTYZi20YO1vDWTZ2fWzAw3HT14dunizBFUwf9Qe37Hb2EmaGkhGHiTRR/qWYTJP/btvbZhqLyENd4Fgny33FwMMiXXidtvRVx2y6CMvlj3zAXiBrJ5kaSj9X4mxokd7H6WsxPTWoNGyC5vwPW4dVmFnA==)
  token-validity-in-seconds: 2592000  # 60 * 60 * 24 * 30 30? -> ?
  refresh-token-validity-in-seconds: 2592000 # 60 * 60 * 24 * 30 30? -> ?
## p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true

--- # prod 환경
spring:
  config:
    activate:
      on-profile: prod

# Oauth 설정
  security:
    oauth2:
      naver:
        client-id: ENC(68K3htZeJ3YepfQoQ9q8Be392V96gJtufq2Qju3lSt0=)
        client-secret: ENC(jOshFL4Sjf0urvS5ZFhR/jrvSMG9Dxdw)
        scope: name,email,age,gender,birthday,birthyear,mobile
        client-name: Naver
        authorization-grant-type: authorization_code
        redirect-url: http://localhost:8080/auth/naver/callback
        authorization: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        user-name-attribute: response


jwt:
  secret: ENC(NMYQFZTvflq8xLXcPokP9JbX2L/7XjXTYZi20YO1vDWTZ2fWzAw3HT14dunizBFUwf9Qe37Hb2EmaGkhGHiTRR/qWYTJP/btvbZhqLyENd4Fgny33FwMMiXXidtvRVx2y6CMvlj3zAXiBrJ5kaSj9X4mxokd7H6WsxPTWoNGyC5vwPW4dVmFnA==)
  token-validity-in-seconds: 900  # 60 * 15 15? -> ?
  refresh-token-validity-in-seconds: 2592000 #1209600 # 60 * 60 * 24 * 30 30? -> ?